name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PUBLIC_TCP_UDP_PORT_AUTH: 5301
  PUBLIC_TCP_UDP_PORT_RECURSOR: 5302

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Version Information
      run: |
        docker --version
        docker-compose --version

    - name: Cache docker images
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-images-${{ hashFiles('.gitmodules') }}

    - name: Build Images
      run: |
        cd $GITHUB_WORKSPACE
        docker-compose build

    - name: Spin up DNS servers
      run: |
        docker-compose up -d

    - name: Install Requirements
      run: |
        pip3 install dnspython requests pytest  # -r requirements.txt
        pip3 freeze

    - name: Setup DNS data
      run: |
        python3 setup.py

    - name: Pytest
      run: python3 -m pytest test
